export const en_msgs = {
    'botao.iniciar': 'Iniciar!',
    id1:{
        desc: 'First stop: Southeast Atlantic Hydrographic Region. Follow me! The Southeast Region has so many of rivers.',
        resp1: 'Lets go!',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Lencol',
        comentario:' Did you know that the Southeast Atlantic Hydrographic Region has 229 thousand squear kilometers? I couldnt walk all that even if I tried.',
        corretas:['resp1'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },

    Lencol:{
        desc: 'Do you know what an aquifer is?',
        resp1: 'Yes!',
        resp2: 'No...',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Lencol2',
        comentario:'',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png'),
    },
    Lencol2:{
        desc: 'See that white part under the rocks? Thats is underground water! Also known as our beloved Aquifer!',
        resp1: 'What else?',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Lencol3',
        comentario:'Do you know what is the worlds biggets aquifer ? R: Its Guarani Aquifer, with an area of 1,2 million square kilometers.',
        corretas:['resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png'),
    },
    Lencol3:{
        desc: ' The water starts draining from the surface until it reaches a point it cant go any deeper.',
        resp1: 'Cool!',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Lencol4',
        comentario:'Do you know what is the worlds biggets aquifer ? R: Its Guarani Aquifer, with an area of 1,2 million squear kilometers.',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png'),
    },
    Lencol4:{
        desc: ' And then it makes this undeground lake. Amazing right? Lets get going then! ',
        resp1: 'To where?',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Arvore',
        comentario:'Do you know what is the worlds biggets aquifer ? R: Its Guarani Aquifer, with an area of 1,2 million squear kilometers.',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png'),
    },
    Arvore:{
        desc: 'Now you decide. Where am I going?',
        resp1: 'Tree',
        resp2: 'River',
        resp3: '',
        resp4: '',
        gameover: '',
        prox: 'Arvore2',
        corretas:['resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png')
    },
    Arvore2:{
        desc: 'Right! The tree will get us from underground with these deep roots... Lets go up?',
        resp1: 'Yes!',
        resp2: 'Changed my mind',
        resp3: '',
        resp4: '',
        gameover: '',
        prox: 'Arvore3',
        corretas:['resp3'],
        imagemFundo: require('../assets/screenBackgrounds/Arvore.png')
    },
    Arvore3:{
        desc: 'Oh! This is really high! Better be carefull not to fall! Where are we heading now?',
        resp1: 'Go back down!',
        resp2: 'Lets get to the leaves!',
        resp3: '',
        resp4: '',
        gameover: '',
        prox: 'Arvore4',
        corretas:['resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Arvore.png')
    },
     
    Arvore4:{
        desc: 'Wow! It is so high, but also so hot! The tree is breathing! You know what this means? It looks like we are going back to the sky!',
        resp1: 'Evapotranspiration!',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: '',
        prox: 'Logo',
        corretas:['resp1'],
        imagemFundo: require('../assets/screenBackgrounds/Folhas.png')
    },
    Logo:{
        desc: 'That was fun! Lets try another path?',
        resp1: '',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: '',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Intro.png')
    },
    sairrio:{
        desc: 'Estou bem o fundo da terra. posso sair por meio de rios, ou ser captado por árvores e por meio de poços para plantações. pra onde eu vou agora',
        resp1: 'absorvido por árvore',
        resp2: 'captado para agricultura',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: '',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    plantaali:{
        desc: 'Eu posso ser usada para muitas coisas, como para regar as plantas e alimentar animais, onde será usada?',
        resp1: 'agrotóxico ruim',
        resp2: 'pesticida bom',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: 'gameover por tal motivo da pergunta 2',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    nsitobem:{
        desc: 'Não me sinto tão bem, tenho que escoar para algum lugar',
        resp1: 'Lençol',
        resp2: 'Rio',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: '',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    fundoterra:{
        desc: 'Estou bem o fundo da terra. posso sair por meio de rios, ou ser captado por árvores e por meio de poços para plantações. pra onde eu vou agora, so nao me sinto muito bem',
        resp1: 'Absorvido por árvore',
        resp2: 'Captado para agricultura',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: 'gameover por tal motivo da pergunta 2',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    sitopior:{
        desc: 'Me sinto pior, tenho que escoar para algum lugar',
        resp1: 'Lençol',
        resp2: 'Rio',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: 'gameover por tal motivo da pergunta 2',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    terra:{
        desc: 'Estou bem o fundo da terra. posso sair por meio de rios, ou ser captado por árvores e por meio de poços para plantações. pra onde eu vou agora',
        resp1: 'absorvido por árvore',
        resp2: 'captado para agricultura',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: '',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },

}