export const ptbr_msgs = {
    'botao.iniciar': 'Iniciar!',
    id1:{
        desc: 'Primeira parada, a Bacia Atlântica Sudeste. Vamos lá! Me sigam! Esta tal de Bacia Atlântica Sudeste tem vários rios.',
        resp1: 'Vamos lá!',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Lencol',
        comentario:'Esta bacia tem uma área de 229 mil quilômetros quadrados. Nossa, eu não conseguiria andar isso tudo não, ficaria bem cansada.',
        corretas:['resp1'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },

    Lencol:{
        desc: 'Vocês sabem o que é um lençol freático?',
        resp1: 'Sim',
        resp2: 'Nao',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Lencol2',
        comentario:'Você sabe qual é o maior manancial do mundo ? R: É o Aquífero Guarani, com uma área de 1,2 milhões de quilômetros quadrados.',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png'),
    },
    Lencol2:{
        desc: 'Você está vendo esta parte branca debaixo da terra. Então, isto é um lençol freático.',
        resp1: 'Que mais?',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Lencol3',
        comentario:'Você sabe qual é o maior manancial do mundo ? R: É o Aquífero Guarani, com uma área de 1,2 milhões de quilômetros quadrados.',
        corretas:['resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png'),
    },
    Lencol3:{
        desc: ' é quando a água vai descendo na terra até um ponto que ela não consegue descer mais.',
        resp1: 'Legal!',
        resp2: 'Nao',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Lencol4',
        comentario:'Você sabe qual é o maior manancial do mundo ? R: É o Aquífero Guarani, com uma área de 1,2 milhões de quilômetros quadrados.',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png'),
    },
    Lencol4:{
        desc: ' E então, faz esses laguinhos debaixo da terra. Tudo bem! Vamos para a próxima parte então. ',
        resp1: 'Para onde?',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: 'gameover por tal motivo da pergunta 1',
        prox: 'Arvore',
        comentario:'Você sabe qual é o maior manancial do mundo ? R: É o Aquífero Guarani, com uma área de 1,2 milhões de quilômetros quadrados.',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png'),
    },
    Arvore:{
        desc: 'Agora você decide. Para onde eu vou agora ?',
        resp1: 'Árvore',
        resp2: 'Rio',
        resp3: '',
        resp4: '',
        gameover: '',
        prox: 'Arvore2',
        corretas:['resp1'],
        imagemFundo: require('../assets/screenBackgrounds/Lencol.png')
    },
    Arvore2:{
        desc: 'Certo, primeiro a árvore vai puxar a gente pelas raízes dela que estão debaixo da terra, e devagar vamos subindo. ?',
        resp1: 'Sim!',
        resp2: 'Mudei de ideia',
        resp3: '',
        resp4: '',
        gameover: '',
        prox: 'Arvore3',
        corretas:['resp3'],
        imagemFundo: require('../assets/screenBackgrounds/Arvore.png')
    },
    Arvore3:{
        desc: 'Eita, aqui está bastante alto, tenho que tomar cuidado para não cair e não me machucar. Para onde vamos agora?',
        resp1: 'Vamos para as folhas!',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: '',
        prox: 'Arvore4',
        corretas:['resp1'],
        imagemFundo: require('../assets/screenBackgrounds/Arvore.png')
    },
     
    Arvore4:{
        desc: 'Nossa aqui é tão alto, mas está tão quente, a plantinha está transpirando, parece que vamos voltar pro céu.',
        resp1: 'Evapotranspiração!',
        resp2: '',
        resp3: '',
        resp4: '',
        gameover: '',
        prox: 'id',
        corretas:['resp1'],
        imagemFundo: require('../assets/screenBackgrounds/Folhas.png')
    },
    ondechover:{
        desc: 'Estou pronto para chover, onde vou ser armazenado?',
        resp1: 'Rio',
        resp2: 'Lago',
        resp3: 'Lençol ',
        resp4: 'Mar',
        gameover: '',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    sairrio:{
        desc: 'Estou bem o fundo da terra. posso sair por meio de rios, ou ser captado por árvores e por meio de poços para plantações. pra onde eu vou agora',
        resp1: 'absorvido por árvore',
        resp2: 'captado para agricultura',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: '',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    plantaali:{
        desc: 'Eu posso ser usada para muitas coisas, como para regar as plantas e alimentar animais, onde será usada?',
        resp1: 'agrotóxico ruim',
        resp2: 'pesticida bom',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: 'gameover por tal motivo da pergunta 2',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    nsitobem:{
        desc: 'Não me sinto tão bem, tenho que escoar para algum lugar',
        resp1: 'Lençol',
        resp2: 'Rio',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: '',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    fundoterra:{
        desc: 'Estou bem o fundo da terra. posso sair por meio de rios, ou ser captado por árvores e por meio de poços para plantações. pra onde eu vou agora, so nao me sinto muito bem',
        resp1: 'Absorvido por árvore',
        resp2: 'Captado para agricultura',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: 'gameover por tal motivo da pergunta 2',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    sitopior:{
        desc: 'Me sinto pior, tenho que escoar para algum lugar',
        resp1: 'Lençol',
        resp2: 'Rio',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: 'gameover por tal motivo da pergunta 2',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },
    terra:{
        desc: 'Estou bem o fundo da terra. posso sair por meio de rios, ou ser captado por árvores e por meio de poços para plantações. pra onde eu vou agora',
        resp1: 'absorvido por árvore',
        resp2: 'captado para agricultura',
        resp3: 'Resposta3',
        resp4: 'Resposta4',
        gameover: '',
        prox: 'id',
        corretas:['resp1','resp2'],
        imagemFundo: require('../assets/screenBackgrounds/countries/Brasil/Southwest/SouthwestZ.png')
    },

}